### ISSUE TITLE
For previous HW

### ISSUE THREAD

**Issue by XXXVivilovesBoba** [emma-data-works/ds-class-intro#17] opened 2021-08-12 18:20 UTC
Hi Emma,
Thanks for being patient and answer my basic question. I just joined the class and still trying to catch up with everything, and it is a lot of stuff for a beginner.
For the HW, # 2. Write a Python program to count the number of even and odd numbers from a series of numbers.
My code is:
numbers = (1, 2, 3, 4, 5, 6, 7, 8, 9)
odd = []
even = []
for num in numbers:
    if num % 2 ==1:
        odd.append(num)
    if num % 2 ==0:
        even.append(num)
        
odd1= len(odd)
even1 = len(even)

print('Number of odd number : {}'.format(odd1))
print('Number of even number : {}'.format(even1))

Your code is:
numbers = (1, 2, 3, 4, 5, 6, 7, 8, 9)
odds = 0
evens = 0
for num in numbers:
    if num % 2:
        odds += 1
    else:
        evens += 1
print('Number of even numbers : {}'.format(evens))
print('Number of odd numbers : {}'.format(odds))

Your code is much shorter than mine, but I do not quite understand your logic here. When you set odds = 0, evens = 0. Are you telling the computer the number starts with 0? 
When I set odd = [], why it does not work?
for the for loop part, why does python understand you want to count the numbers? 
Why do you not need to set if num % 2 == 0 and python still understand you?

**Comment by emma-data-works** [comment] 2021-08-13 18:36
Welcome to the class! Feel free to ask any question here:)

1. the `odds` and `evens` I was using have a different meaning than yours - mine is simply a counter that starts from 0, while yours is a list to store the actual numbers. Since the problem is not asking to return the odd or even numbers, I'm just counting the # of odd/even numbers and not storing them. The counters start from 0 as we there is 0 odd number and 0 even number before we iterate throughout the list given. 

2. the difference is mainly on `odd.append(num)` v.s. `odds += 1`. The former appends the number into initialized list, while the latter adds 1 to the counter (integer). If you set `odds=[]` and run the same code, it won't be able to add a list and an integer so it wouldn't word.

3. we covered in previous classes that any condition in `if-elif-else` clause will be resolved to a boolean variable for the condition to be evaluated, so `if num % 2 == 0` is resolving `num % 2` as a boolean variable. We mentioned in class01 that 

> Almost everything in python is mapped to a boolean value, even if it's not boolean type. This could be checked using `bool()` function. Empty strings, zero, and empty collection (we'll cover later) will have `False` value.

So if `num % 2` returns 1, it will be a `True` in boolean, so purely from results, we can shorten `num % 2  == 1` to `num % 2`.

**Closed as completed** 2021-08-15 20:09 UTC
